# Generated by Django 4.1.3 on 2022-11-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=0)),
                ('ISBN', models.CharField(max_length=150)),
                ('book_name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('book_author', models.CharField(max_length=150)),
                ('publication_year', models.IntegerField(default=0)),
                ('publisher', models.CharField(max_length=150)),
                ('page_count', models.IntegerField(default=0)),
            ],
        ),
    ]
