# Generated by Django 4.1.3 on 2022-11-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_URL',
            field=models.URLField(default='#', max_length=250),
            preserve_default=False,
        ),
    ]
